### PR TITLE
Fixed error when receiving SOAP messages from Postman/SoapUI

### PR DESCRIPTION
**Pull request by DazEdword**
First of all, thanks for creating SoapCore! I had been having problems when passing an object as part of the requests as seen in your ComplexModel input when such request originated from external software, let's say Postman or SoapUI. 

### How to replicate

- In the sample solution, run the server normally.
- Use postman to send a request like this:

Type: POST
Format: raw, XML (text/xml)

```<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:PingComplexModel>
         <!--Optional:-->
         <tem:inputModel>
            <!--Optional:-->
            <tem:IntProperty>10</tem:IntProperty>
            <tem:StringProperty>hi</tem:StringProperty>
         </tem:inputModel>
      </tem:PingComplexModel>
   </soapenv:Body>
</soapenv:Envelope>
```

Error `“This message cannot support the operation because it has been read”` will occur.

### Fix

It turns out that the error was originated by the message being read twice, which was easily solved by creating a buffered copy and using the copy to determine the soapAction. 

Hope this helps!

### CODE REVIEW

**Comment by kotovaleksandr** [comment]
Please check PR #65, its your case?

**Comment by DazEdword** [comment]
I have tested PR #65 and sadly it doesn't seem to fix my case.

**Comment by kotovaleksandr** [comment]
I cant reproduce this issue on latest changes. Trying in Postman.

Service url:
`http://localhost:5050/Service.svc`

Request body:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:PingComplexModel>
         <!--Optional:-->
         <tem:inputModel>
            <!--Optional:-->
            <tem:IntProperty>10</tem:IntProperty>
            <tem:StringProperty>hi</tem:StringProperty>
         </tem:inputModel>
      </tem:PingComplexModel>
   </soapenv:Body>
</soapenv:Envelope>
```

Response body:
```xml
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><PingComplexModelResponse xmlns="http://tempuri.org/"><PingComplexModelResult xmlns:a="http://schemas.datacontract.org/2004/07/Models" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><a:FloatProperty>1.70141173E+38</a:FloatProperty><a:StringProperty>9a872769-181a-4a06-b46c-87f7329c69b2</a:StringProperty></PingComplexModelResult></PingComplexModelResponse></s:Body></s:Envelope>
```
Its work fine.

Yourr PR can break scenarios with DataContractSerializer and make copy of message is not effective solution.

Please provide full details for reproduce your problem, i will fix it.

**Comment by DazEdword** [comment]
Definitely strange, I have just checked out master branch, ensured it has latest changes and made the very exact request you added above. Result:

```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <s:Fault>
            <faultcode>s:Client</faultcode>
            <faultstring>This message cannot support the operation because it has been read.</faultstring>
            <detail />
        </s:Fault>
    </s:Body>
</s:Envelope>
```

Commit: 151abd9

Server output:

```
warn: SoapCore.SoapEndpointMiddleware[0]
      This message cannot support the operation because it has been read.
System.InvalidOperationException: This message cannot support the operation because it has been read.
   at System.ServiceModel.Channels.Message.EnsureReadMessageState()
   at System.ServiceModel.Channels.Message.GetReaderAtBodyContents()
   at SoapCore.SoapEndpointMiddleware.GetRequestArguments(Message requestMessage, OperationDescription operation, Dictionary`2& outArgs) in C:\Users\eduardo.garabito.LAN\Documents\Repos\soapcore-custom\src\SoapCore\SoapEndpointMiddleware.cs:line 172
   at SoapCore.SoapEndpointMiddleware.<ProcessOperation>d__9.MoveNext() in C:\Users\eduardo.garabito.LAN\Documents\Repos\soapcore-custom\src\SoapCore\SoapEndpointMiddleware.cs:line 124
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 291.2516ms 500 text/xml
```

Made the request via Postman (latest version), sending details via POST http://localhost:5050/Service.svc as raw XML (text/xml).

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:PingComplexModel>
         <!--Optional:-->
         <tem:inputModel>
            <!--Optional:-->
            <tem:IntProperty>10</tem:IntProperty>
            <tem:StringProperty>hi</tem:StringProperty>
         </tem:inputModel>
      </tem:PingComplexModel>
   </soapenv:Body>
</soapenv:Envelope>
```

Let me know if I can provide any details.

**Pull request closed without merging**
