### PR TITLE
Add support for circular references in datacontract objects

### LINKED ISSUE #302: Add support for circular references in data contracts
Hi!

First of all, thank you for your project.

It appears that circular references in datacontract objects are not well supported, and always lead to a StackOverflowException. This seems to be due to the way recursivity is handled while parsing objects in the `MetaWCFBodyBuilder` class.

Short example :
```csharp
[DataContract]
public class CircularReferenceFirstObject
{
    [DataMember]
    public CircularReferenceSecondObject SecondObject { get; set; }
}
```

references 
```csharp
[DataContract]
public class CircularReferenceSecondObject
{
    [DataMember]
    public CircularReferenceFirstObject FirstObject { get; set; }
}
```
which references `CircularReferenceFirstObject`. StackOverflow is raised on first call.

### PR DESCRIPTION
**Pull request by apatenotre**
Fixes #302 

Solution : store type in dictionary before the recursive call

### CODE REVIEW

**Comment by kotovaleksandr** [comment]
Hi @apatenotre Please, fix conflicts. Thanks for your help!

**Comment by apatenotre** [comment]
Hi @kotovaleksandr,
 work in progress, will fix this tonight and let you know!

**Comment by apatenotre** [comment]
> 
> 
> Hi @apatenotre Please, fix conflicts. Thanks for your help!

All good

**Comment by apatenotre** [comment]
Actually, moving it back to WIP as I think I found a regression. I will clean it tomorrow

**Comment by apatenotre** [comment]
Ok, should be good now.
The idea is that tracking of objects discovered while building the wsdl was incorrectly done. `_complexTypeToBuild` was used to detect circular references, but was set even before the type was read for the first time. So types could be skipped when they were not root while discovered. So I introduced a dedicated hashset

**Pull request merged**
