### PR TITLE
default logging to debug

### PR DESCRIPTION
**Pull request by jnov14**
default logging to debug for request/receive #1041

### CODE REVIEW

**Comment by Yozer** [comment]
I would level them as info. Default logging level for asp.net core incoming requests is also Information.
You can configure what SoapCore logs on your side by for example setting minimum logging level for SoapEndpointMiddleware to Warn.

**Comment by jnov14** [comment]
@Yozer Do you have an example of setting minimum log level to Warn for SoapEndpointMiddleware?

**Comment by Yozer** [comment]
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "SoapCore.SoapEndpointMiddleware": "Warning" 
    }
  }
}
```

**Comment by jnov14** [comment]
Ahh, thank you!

**Pull request closed without merging**
