### PR TITLE
fix #319 by switching serialization order of return param and out params

### LINKED ISSUE #319: Serialization order of return value vs ref parameters seems wrong
When a function both has a result as out/ref parameters the response appears to be serialized in the wrong order, in any case it is not possible to consume the services from a regular dotnet client.

e.g.
[OperationContract]
TBRSFlightData[] GetTodaysFlightsByType(ref string SecurityToken);

response gets serialized like this:

\<GetTodaysFlightsByTypeResponse xmlns="http://tempuri.org/">
    \<SecurityToken>xxxxxxx\</SecurityToken>
    \<GetTodaysFlightsByTypeResult .....
     \<a:TBRSFlightData>
        ........
      \</a:TBRSFlightData>
    \</GetTodaysFlightsByTypeResult>
\</GetTodaysFlightsByTypeResponse>"

but it should be like this:

\<GetTodaysFlightsByTypeResponse xmlns="http://tempuri.org/">
   \<GetTodaysFlightsByTypeResult .....
      \<a:TBRSFlightData>
      ........
      \</a:TBRSFlightData>
    \</GetTodaysFlightsByTypeResult>
    \<SecurityToken>xxxxxxx</SecurityToken>
\</GetTodaysFlightsByTypeResponse>

After creating a fork and changing the serialization order I am able to consume the service with our existing client.

### PR DESCRIPTION
**Pull request by DominicUllmann**
WCF client can only deserialize out/ref parameter together with return parameter, if serialized in the correct order. 
Changing result and out/ref parameter order is necessary so that ref/out parameters are not deserialized as null.

This will fix the issue #319

### CODE REVIEW

**Review by elca-lan — APPROVED** [review]
This is essentially the same change that @lokasoft already did in his fork and I think it makes sense like this because the old way is simply not conforming to the spec as far as I can tell.

**Comment by StevenBonePgh** [comment]
Would it be possible to push a new package with this change?  Thanks!

**Comment by kotovaleksandr** [comment]
@StevenBonePgh @elca-lan https://www.nuget.org/packages/SoapCore/1.1.0.4-beta

**Comment by DominicUllmann** [comment]
Great, thanks a lot for the new release. It works well 👍

**Comment by sadollah1** [comment]
I install the beta version but ı still need the change order number manually.The problem is still not solved for me. Any advice.

**Comment by DominicUllmann** [comment]
> 
> 
> I install the beta version but ı still need the change order number manually.The problem is still not solved for me. Any advice.

How did you test that? It works perfectly for me with a wcf client. How does your service interface and client look like? What do you mean by changing the order manually?

**Pull request merged**
