### PR TITLE
[in progress] fix ref and out parameters deserialization

### PR DESCRIPTION
**Pull request by DmitryBryluk**
> issue: incorrect handle of mixture of multiple out/ref/value params while desearializing them and passing to service method invokation

fixed

> issue: missing out/ref params in schema generation

fixed with the same logic as above. however schema generation still incomplete, misses content of some types, and also need to get rid of '&' characters at the end of out/ref types. but this is another story.

to be done:
- tests

[issue/discussion](https://github.com/DigDes/SoapCore/issues/114)

[another issue:](https://github.com/DigDes/SoapCore/issues/116) perhaps I will implement something like [LegacyCompatibility] attribute to control additional envelope, need a bit more exploration. indeed other operations may be broken.

### CODE REVIEW

**Comment by kotovaleksandr** [comment]
@DmitryBryluk Please, 

- move Serialization tests to SoapCore.Test
- remove reference to Model from tests
- test TestPingComplexModelOutAndRefSerialization not working on my machine (test started before server initialized), maybe reason in row host.RunAsync()

Temporarily i remove Serialization tests project because build are broken, I can not understand why.

**Comment by kotovaleksandr** [comment]
I don't know how it works - build passed, without any changes in code.

**Comment by DmitryBryluk** [comment]
> move Serialization tests to SoapCore.Test

it uses xunit, will it be working together in one project with other testing system?

> remove reference to Model from tests

we have to maintain copy of models in tests? these models are used in tests along with service contract

> test TestPingComplexModelOutAndRefSerialization not working on my machine (test started before server initialized

perhaps service have not much time to start, try Thread.Sleep(...) after host.RunAsync

> build passed, without any changes in code

seems some non-code related issues, when looking to travis logs

...still working on this

**Comment by kotovaleksandr** [comment]
> move Serialization tests to SoapCore.Test
>
> it uses xunit, will it be working together in one project with other testing system?

Because exists tests worked with mstest reasonably add new tests to mstest project. If you know more one reason why xunit must better than mstest for our project - you can port exists test to xunit.
> remove reference to Model from tests
> 
> we have to maintain copy of models in tests? these models are used in tests along with service contract

Please copy Model from demo app to tests. Samples is not equals to tests, i planned simplify and describe demo application, currently its unreadable code.
> test TestPingComplexModelOutAndRefSerialization not working on my machine (test started before server initialized
> 
> perhaps service have not much time to start, try Thread.Sleep(...) after host.RunAsync
> 
> build passed, without any changes in code
> 
> seems some non-code related issues, when looking to travis logs
> 
> ...still working on this

Its another reason why additional test project is bad, in exists tests its problem solved and tests worked on local machines and travis.

Thanks for you help for our project, this is very important for us and we are very grateful!

**Comment by DmitryBryluk** [comment]
ok, try asap

**Comment by DmitryBryluk** [comment]
completed [here](https://github.com/DigDes/SoapCore/pull/120)

**Pull request merged**
