### PR TITLE
Remove extra scope while getting IMessageInspector2.

### LINKED ISSUE #1088: Extra scope for IMessageInspector2.
Hi.
I don't understand what the purpose of this change in SoapEndpointMiddleware.cs was and in what cases might an extra scope be needed. But after that there is logical error. If we want to get implementation from DI in service implementation, we will get new implementation of IMessageInspector2 instead of existed. We need it to add some behavior in runtime and accumulate logs (request, some process logs, reply).
I think IMessageInspector2 should be in request scope.

```C#
using (IServiceScope scope = serviceProvider.CreateScope())
{
	var messageInspector2s = scope.ServiceProvider.GetServices<IMessageInspector2>();
	correlationObjects2 = messageInspector2s.Select(mi =>
		(inspector: mi, correlationObject: mi.AfterReceiveRequest(ref requestMessage, _service)))
		.ToList();
}
```

### PR DESCRIPTION
**Pull request by avoronin565**
fix: #1088

### CODE REVIEW

**Comment by andersjonsson** [comment]
Yep, I think you're right about the extra scope not being needed

**Comment by andersjonsson** [comment]
Thanks!

**Comment by avoronin565** [comment]
Could you please make release with this fix? Thanks.

**Comment by avoronin565** [comment]
Dear friend, could you please make release please? Need these fix very much. Thank you!

**Comment by andersjonsson** [comment]
> Dear friend, could you please make release please? Need these fix very much. Thank you!

Totally missed this. Sorry.
New release is out now

**Pull request merged**
