### PR TITLE
fix for processing soap-1.2 message

### PR DESCRIPTION
**Pull request by itn3000**
resolving soapaction logic and response's namespace

### CODE REVIEW

**Comment by kotovaleksandr** [comment]
Hi, can you fix conflicts and resend PR?

**Comment by itn3000** [comment]
OK, I will fix. Thank you for pointing it out.

**Comment by itn3000** [comment]
Fixed. Could you review it?

**Comment by Hallupa** [comment]
I have the latest version (0.97) but I still get errors with Soap 1.2 (Soap 1.1 is fine) - did this fix go into the 0.97 release?

**Pull request merged**
