### PR TITLE
Messagecontract, wrapped and parameters

### PR DESCRIPTION
**Pull request by jonas-jaderberg**
#575 I think is in the same are as I was fixing earlier so tried to extend my tests to include similar case as @imqqmi mention.
I think I found issues related to handle parameters for MessageContracts and wrapped parameters this and might fix issue #575
Can someone check/verify that this looks correct?

### CODE REVIEW

**Comment by imqqmi** [comment]
I've tried this commit but it doesn't change the outcome for me unfortunately (issue #575), the parameter is still empty.

I've cleaned and rebuild the SoapCore library but that didn't change things either.

**Comment by jonas-jaderberg** [comment]
@imqqmi, hmm strange if you look at the test cases / models I addad, test Soap11MessageContract isn't that very similar to your case?

**Comment by imqqmi** [comment]
It doesn't test receiving the parameters sent in the request. This is the body that is sent in the request (empty body):
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header/>
  <soapenv:Body/>
</soapenv:Envelope>
```

And it responds with OK, and that's what I've been able to do too, but it doesn't receive the request parameters. So a correct test would be sending a [messagecontract] with a [MessageBodyMember] with for example a string or int. Then read the string or int and send it to the response. If the response is the same as was sent, the test completes successfully.

**Comment by jonas-jaderberg** [comment]
Wrong test case I think. This one in SoapCore.Tests.MessageContract does
	public async Task Soap11MessageContract()
		{
			const string body = @"<soapenv:Envelope xmlns:soapenv=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:tem=""http://tempuri.org"">
  <soapenv:Header/>
  <soapenv:Body>	  
    <tem:MessageContractRequest>	   
        <tem:ReferenceNumber>1</tem:ReferenceNumber>
    </tem:MessageContractRequest>
  </soapenv:Body>
</soapenv:Envelope>
";
			using (var host = CreateTestHost())
			using (var client = host.CreateClient())
			using (var content = new StringContent(body, Encoding.UTF8, "text/xml"))
			using (var res = host.CreateRequest("/Service.asmx").AddHeader("SOAPAction", @"""DoRequest""").And(msg => msg.Content = content).PostAsync().Result)
			{
				res.EnsureSuccessStatusCode();

				var response = await res.Content.ReadAsStringAsync();
				Assert.IsTrue(response.Contains("MessageContractResponse"));
				Assert.IsTrue(response.Contains("ReferenceNumber>1</"));
			}
		}

**Comment by imqqmi** [comment]
Thanks for the heads up, didn't know how PRs worked. I assumed it was already merged into dev branch, my bad. I'll investigate further how it is done in the test so I can change my code to match it. Thanks!

**Comment by imqqmi** [comment]
After looking at the Soap11MessageContract() test, is seems it doesn't pass through the deserializer, so the defined class/model isn't created and hydrated with the values in this test, it only checks the response xml content body for containing the parameter. Would be great if the test also covers deserialization.

**Comment by jonas-jaderberg** [comment]
Yes, these are "raw" tests. There are other serialization test available, not sure if they cover your case

**Comment by jonas-jaderberg** [comment]
Anyway, I think this can me merged into develop

**Comment by kishorekodru** [comment]
is this merged to dev branch?

**Comment by kotovaleksandr** [comment]
@kishorekodru yes

**Comment by kishorekodru** [comment]
I just got the latest from dev branch and i still get the message where request / part is empty 
</wsdl:types>
<wsdl:message name="NPADRVBKPort_NPADRVBKOperation_InputMessage"/>
<wsdl:message name="NPADRVBKPort_NPADRVBKOperation_OutputMessage">
<wsdl:part name="parameters" element="tns:NPADRVBKOperationResponse"/>
</wsdl:message>

**Comment by kishorekodru** [comment]
<wsdl:message name="NPADRVBKPort_NPADRVBKOperation_InputMessage"/> doesnt have part name/element.

**Comment by kishorekodru** [comment]
@kotovaleksandr  i got the latest from dev branch. still doesnt generate the part? Any suggestions? 
            app.UseSoapEndpoint<NPADRVBKService>("/Intake/npadrvbk", new BasicHttpBinding(), SoapSerializer.XmlSerializer);

This is what I have .

**Comment by jonas-jaderberg** [comment]
@kishorekodru, how does your contract/interface look like?
If there is now input parameter, isn't the part unnecessary? 
I have a wsdl with an operation without parameter and it looks like
..
<message name="pullSnapshotDataInputMessage"/>
<message name="pullSnapshotDataOutputMessage">
<part name="return" element="tns:pullSnapshotDataOutput"/>
</message>
..
and it's a valid WSDL and complies to WS-I.

**Comment by kishorekodru** [comment]
Interface  : 
    [ServiceContract]
    interface NPADRVRLInterface
    {
        [OperationContract]
        public NPADRVRLData NPADRVRLOperation(NPADRVRLData input);
    }

Impl: 
    public class NPADRVRLService : NPADRVRLInterface
    {
        public NPADRVRLData NPADRVRLOperation(NPADRVRLData input)
        {
            IntakeSOAPService svc = new IntakeSOAPService();
            return (NPADRVRLData)svc.ProcessProgram(input, "NPADRVRL");
        }
    }

I am new to .NET Core and it has been annoying with only response being generated and not input in the wsdl

**Comment by jonas-jaderberg** [comment]
Ok, I misunderstood thought you had no input parameter. But, you have. How does your NPADRVRLData look like, is it a MessageContract?

**Comment by kishorekodru** [comment]
It is a dataContract. Should i make it MessageContract?

**Comment by jonas-jaderberg** [comment]
If you like use SoapSerializer.XmlSerializer MessageContract gives more control. Datacontracts is used with DataContractSerializer but not sure what happens if you mix

**Pull request merged**
