### PR TITLE
Reengineer fix for xmlnamespacemanager corruption

### PR DESCRIPTION
**Pull request by andersjonsson**
@TsengSR @kotovaleksandr 

PR based on the discussion in #744
As far as I can tell `GetXmlNamespaceManager()` in `SoapEndpointMiddleware` is called everywhere that an `XmlNamespaceManager` is needed. That instance doesn't seem to be stored in any singletons.

It's unfortunate to revert this change between nuget versions, but I think it's worth it.

What do you think?

This change will be tested in our staging environment tomorrow morning, so we'll know for sure that it fixes the original issue.

### CODE REVIEW

**Comment by andersjonsson** [comment]
Yep, this fix seems to do the trick also and I feel much better about it.
If we want pure performance it should be fairly easy to cache the namespaces per endpoint later.

**Comment by andersjonsson** [comment]
I came across another potential bug, but I filed a separate issue for that

**Comment by andersjonsson** [comment]
Had to convert it back to draft. I realize we need to do some more testing on our end.

**Comment by andersjonsson** [comment]
Testing is complete. Works as intended

**Comment by kotovaleksandr** [comment]
@TsengSR What you say? Looks good?
I'm sorry, it's my bad that i didn't look well enough at the previous PR. i should have seen performance problem with lock:(

**Comment by TsengSR** [comment]
> @TsengSR What you say? Looks good? I'm sorry, it's my bad that i didn't look well enough at the previous PR. i should have seen performance problem with lock:(

Yea, looks fine

**Pull request merged**
