### PR TITLE
Added Optional Custom Serializer in Soap Core

### PR DESCRIPTION
**Pull request by ankitkmrpatel**
Added Custom Soap Core Serializer using DI
If Custom Soap Core Serializer NOT found, Then Fall back for default Soap Core Serializer

### CODE REVIEW

**Comment by andersjonsson** [comment]
Please fix the build errors in the test project and I will take a look.
I would also like you to add a test case to make sure that it works and won't break by future changes

**Comment by andersjonsson** [comment]
And thank you for the PR 😄

**Comment by ankitkmrpatel** [comment]
Hi,

Fixed build error(s) for Middleware in test proj and added new test case for Serializer.

Let me know if there is anything to add.

**Comment by andersjonsson** [comment]
There are plenty of failing tests. Please take a look and fix that

**Comment by ankitkmrpatel** [comment]
Fixed! and Updated Docs for Latest Code.

**Comment by ankitkmrpatel** [comment]
@andersjonsson  any comments?

**Comment by andersjonsson** [comment]
I think it looks fine. I would like you to change the name though. `SoapCoreSerializer` is a bit too close to `SoapSerializer`. Since it serializes input parameters I think that should be reflected in the name in some way.

**Comment by ankitkmrpatel** [comment]
Hi @andersjonsson 

Changed from `ISoapCoreSerializer` to `IXmlSerializationHandler`, which emphasizes serialization without explicitly mentioning "input parameter" while still conveying the purpose of the interface.

**Comment by ankitkmrpatel** [comment]
Hi @andersjonsson,

Changed from `ISoapCoreSerializer` to `IXmlSerializationHandler`, which emphasizes serialization without explicitly mentioning "input parameter" while still conveying the purpose of the interface.

**Comment by andersjonsson** [comment]
I think I'm ready to merge this. There are conflicts in SoapCoreOptions.cs that has to be resolved first though

**Comment by ankitkmrpatel** [comment]
@andersjonsson any news on this?

**Comment by andersjonsson** [comment]
The conflicts are still there. Please resolve them, then I can merge this branch

**Comment by ankitkmrpatel** [comment]
@andersjonsson Resolved the conflicts and updated the code. Could you look and let me know if you need anything else?

**Comment by andersjonsson** [comment]
Thank you!

**Pull request merged**
