### PR TITLE
fix extra xml response element

### PR DESCRIPTION
**Pull request by DmitryBryluk**
for old style calls with single return value and input param there is extra result tag for XmlSerializer:
```
SomeMethodResponseType SomeMethod(SomeMethodRequestType)

<SomeMethodResponseType>
    <SomeMethodResult> <= extra element
        ... contents of SomeMethodResponseType ...
    </SomeMethodResult> <= extra element
</SomeMethodResponseType>
```

fixed this

### CODE REVIEW

**Comment by ramondeallima** [comment]
Does it still work?

I'm getting it as extra tags yet.

Do I need to change anything in my code?

**Comment by ramondeallima** [comment]
@DmitryBryluk  

Does it still work?

I'm getting it as extra tags yet.

Do I need to change anything in my code?

**Comment by DmitryBryluk** [comment]
try looking https://github.com/DigDes/SoapCore/blob/master/src/SoapCore.Tests/Serialization/Models.Xml/ISampleService.cs

there are several ways to do what you need, at least one of them have to work

**Comment by ramondeallima** [comment]
Thanks bro! I will verify

**Comment by ramondeallima** [comment]
Case somebody have this problem, the code below worked for me.

`
		// old style call, when all in/out params are packed into single request/response params		// both styles are completely compatible, if we have same method name		//   and req/resp classes as {MethodName}{Request|Response}		// produced/consumed xml response is compatible with legacy wcf/ws		// this operation contract is exactly as in legacy wcf/ws sources and can be consumed there		// to avoid extra envelope element, mark request/reponse type as [MessageContract] and do not use ref/out params		//   otherwise compatibility will be broken		//   (effective only for XmlSerializer)		[OperationContract(Action = ServiceNamespace.Value + nameof(PingComplexModelOldStyle), ReplyAction = "*")]		[XmlSerializerFormat(SupportFaults = true)]		PingComplexModelOldStyleResponse PingComplexModelOldStyle(			PingComplexModelOldStyleRequest request);

`

**Comment by ramondeallima** [comment]
@DmitryBryluk 

Thanks for your last help, I managed to solve it with one of the examples.

image

However, I have a similar problem for the request XML generated in SoapUI.

The tags are:

<! - Optional: ->

<has: model>

I managed to remove the comment <! - Optional: -> using the decorator [DataMember (IsRequired = true)] with DataContractSerializer, but I haven't found anything similar for XmlSerializer.

But the main thing would be to remove the <has:model>.

I tried some examples of the last link, but nothing worked, I believe it's just for the reponse

**Comment by DmitryBryluk** [comment]
perhaps it is just wrong contract generation by SoapCore, if you are talking about what SoapUI auto generated from your endpoint. just fill correct xml disregarding what SoapUI got from SoapCore and it have to be fine. otherwise no idea

**Comment by wahajahmedofficial** [comment]
It is still cant be fixed for me. i am still having that extra result field. it would be great if you can upload an example code so @DmitryBryluk

**Comment by natghi2010** [comment]
> @DmitryBryluk
> 
> Thanks for your last help, I managed to solve it with one of the examples.
> 
> image
> 
> However, I have a similar problem for the request XML generated in SoapUI.
> 
> The tags are:
> 
> <! - Optional: ->
> 
> <has: model>
> 
> I managed to remove the comment <! - Optional: -> using the decorator [DataMember (IsRequired = true)] with DataContractSerializer, but I haven't found anything similar for XmlSerializer.
> 
> But the main thing would be to remove the has:model.
> 
> I tried some examples of the last link, but nothing worked, I believe it's just for the reponse

how did you do it?

**Pull request merged**
