### PR TITLE
Perform case insensitive dictionary lookup of service names from `WebServiceWSDLMapping`

### LINKED ISSUE #700: KeyNotFoundException when case insensitive service WSDL requested with WsdlFileOptions configured
`SoapEndpointMiddleware.ProcessMetaFromFile()` throws a `System.Collections.Generic.KeyNotFoundException` when a service has been registered as `caseInsensitivePath: true` and a `GET` request is made for the WSDL with a URL that does not match exactly the service name in the `WebServiceWSDLMapping` dictionary.

Example:

```cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
  WsdlFileOptions options = new WsdlFileOptions
  {
    UrlOverride = string.Empty,
    VirtualPath = string.Empty,
    WebServiceWSDLMapping = new Dictionary<string, WebServiceWSDLMapping>
    {
      {
        "CaseInsensitiveService.svc", new WebServiceWSDLMapping
        {
          SchemaFolder = "/WsdlFromFile/WSDL",
          WsdlFile = "SnapshotPull.wsdl",
          WSDLFolder = "/WsdlFromFile/WSDL"
        }
      }
    },
    AppPath = env.ContentRootPath
  };

  app.UseSoapEndpoint(_serviceType, "/CaseInsensitiveService.svc", new BasicHttpBinding(), SoapSerializer.DataContractSerializer, true, null, options);

  app.UseMvc();
}
```

```bash
curl https://www.example.com/CaseInsensitiveService.svc # 200 OK
curl https://www.example.com/caseinsensitiveservice.svc # 500 Internal Server Error
```

Stack:

```
crit: SoapCore.SoapEndpointMiddleware[0]
      An error occurred when trying to service a request on SOAP endpoint: /caseinsensitiveservice.svc
System.Collections.Generic.KeyNotFoundException: The given key 'caseinsensitiveservice.svc' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SoapCore.SoapEndpointMiddleware`1.ProcessMetaFromFile(HttpContext httpContext)
   at SoapCore.SoapEndpointMiddleware`1.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
```

### PR DESCRIPTION
**Pull request by WolfyUK**
Closes #700

### CODE REVIEW

**Comment by tibel** [comment]
Wouldn't it be simple to initialize `WebServiceWSDLMapping` dictionary with an OrdinalIgnoreCase comparer?

**Comment by kotovaleksandr** [comment]
@WolfyUK I agree with @tibel . Initialize dictionary with ignore case comparer - right way.

**Comment by WolfyUK** [comment]
@tibel You learn something new every day! Your proposal is much better.

**Comment by Vertygo** [comment]
Case insensitive search should be performed if `CaseInsensitivePath = true`, otherwise it should probably function as it is now.

**Comment by WolfyUK** [comment]
I'm not in a position to revisit this, and a year later this is probably no longer relevant. PR will be closed.

**Pull request closed without merging**
