### PR TITLE
Fix for issue #435: Null values in request for header members.

### PR DESCRIPTION
**Pull request by RafalChmielewski**
Quick fix, hope is self-explanatory.

### CODE REVIEW

**Comment by kotovaleksandr** [comment]
@RafalChmielewski Please, check and fix tests

**Comment by augustowski-k** [comment]
It should be enough to rebase onto develop now.

**Comment by RafalChmielewski** [comment]
Thanks @augustowski-k looks it is working now! @kotovaleksandr is it possible to do a nuget publish with this asap?

**Comment by kotovaleksandr** [comment]
> 
> 
> Thanks @augustowski-k looks it is working now! @kotovaleksandr is it possible to do a nuget publish with this asap?

Thanks! https://www.nuget.org/packages/SoapCore/1.0.0.3-alpha

**Comment by RafalChmielewski** [comment]
Great! Thank you.

**Pull request merged**
