### PR TITLE
bugfix: complex type with a member of a complex type decorated per XmlElementAttribute with custom name breaks custom names of the members specified per XmlElementAttributes of the sub-complex type

### PR DESCRIPTION
**Pull request by edgridin**
Having a complex type (please see ComplexComplexType in the suppled unit test CheckComplexComplexTypeWithCustomXmlNamesWsdl) with a member being itself a complex type (ComplexType), which is configured to have a custom name 'complex' specified by XmlElement, on WSDL generation with XmlSerializer overwrites the custom names and property names, specified by ComplexType, by the name 'complex', producing following definition

<xsd:complexType name="ComplexType">
        <xsd:sequence>
          <xsd:element minOccurs="1" maxOccurs="1" name="complex" type="xsd:int" />
          <xsd:element minOccurs="0" maxOccurs="1" name="complex" type="xsd:string" />
          <xsd:element minOccurs="0" maxOccurs="1" name="complex" type="xsd:base64Binary" />
          <xsd:element minOccurs="1" maxOccurs="1" name="complex" type="xsd:string" />
        </xsd:sequence>
      </xsd:complexType>

correct would be (and is achieved by this fix)

<xsd:complexType name="ComplexType">
        <xsd:sequence>
          <xsd:element minOccurs="1" maxOccurs="1" name="IntProperty" type="xsd:int" />
          <xsd:element minOccurs="0" maxOccurs="1" name="stringprop" type="xsd:string" />
          <xsd:element minOccurs="0" maxOccurs="1" name="mybytes" type="xsd:base64Binary" />
          <xsd:element minOccurs="1" maxOccurs="1" name="MyGuid" type="xsd:string" />
        </xsd:sequence>
      </xsd:complexType>

### CODE REVIEW

**Comment by andersjonsson** [comment]
Could you please update your branch from the latest "develop"? Needed to fix some things to make CI work

**Comment by andersjonsson** [comment]
Merged!
Thank you for this fix

**Comment by edgridin** [comment]
@andersjonsson , thank you for accepting the fix and for the support of SoapCore, it helps me a lot in my current project

**Comment by edgridin** [comment]
@andersjonsson , maybe a small question - do you already know, if you'll publish the bugfix on Nuget? If not, when would you publish the next release of the package?

**Comment by andersjonsson** [comment]
Tried to publish but the api key needs to be updated. I don't have access to that but hopefully it can be sorted quickly

**Comment by andersjonsson** [comment]
Fixed. New version is available on nuget now
https://www.nuget.org/packages/soapcore

**Comment by edgridin** [comment]
thank you!

**Pull request merged**
