### PR TITLE
XmlSerializer WSDL: Fix generated schema for DateTimeOffset

### LINKED ISSUE #1013: XmlSerializer WSDL for DateTimeOffset invalid
Let's say there is a type such as the following:

```csharp
public class Hello
{
    public DateTimeOffset TimeStamp { get; set; } = DateTimeOffset.Now;
}
```

SoapCore currently will generate the following WSDL for it:

```xml
<xsd:complexType name="Hello">
  <xsd:sequence>
    <xsd:element xmlns:q1="http://schemas.datacontract.org/2004/07/System" minOccurs="1" maxOccurs="1" name="TimeStamp" type="q1:DateTimeOffset"/>
  </xsd:sequence>
</xsd:complexType>
```
and further below:
```xml
<xsd:schema xmlns:tns="http://schemas.datacontract.org/2004/07/System" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/System">
  <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
  <xsd:complexType name="DateTimeOffset">
    <xsd:annotation>
      <xsd:appinfo>
        <IsValueType xmlns="http://schemas.microsoft.com/2003/10/Serialization/">true</IsValueType>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="DateTime" type="xsd:dateTime"/>
      <xsd:element minOccurs="1" maxOccurs="1" name="OffsetMinutes" type="xsd:short"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="DateTimeOffset" nillable="true" type="tns:DateTimeOffset"/>
</xsd:schema>
```

This schema corresponds to the XML that the DataContractSerializer generates, but it does not correspond to the XML that the XmlSerializer generates.

The actual SOAP XML that is transferred is the following:
```xml
<Hello>
  <TimeStamp>2024-02-08T09:55:41.2527621+01:00</TimeStamp>
</Hello>
```

As you can see, the XML generated by the XmlSerializer does not correspond to the WSDL that is generated.

### PR DESCRIPTION
**Pull request by vidrenning**
XmlSerializer will serialize a DateTimeOffset simply as a string.

Adjusted the DateTimeOffset test so that it works for both, DataContractSerializer and XmlSerializer.

Fixes #1013

### CODE REVIEW

**Comment by andersjonsson** [comment]
Seems to be the right thing to do! Thanks!

**Comment by vidrenning** [comment]
Thank you for merging! Would it be possible to build a new NuGet package with the latest changes? Having an officially released NuGet package available would make deployment much easier for my situation.🙂

**Comment by andersjonsson** [comment]
> Would it be possible to build a new NuGet package with the latest changes? 

Sure! I'll try to get that done in a bit

**Comment by vidrenning** [comment]
Great, thank you! 🙂

**Comment by andersjonsson** [comment]
Done!

**Comment by vidrenning** [comment]
Thank you very much, unfortunately I have found another issue (#1015). Well that's life 😅.

**Pull request merged**
