### PR TITLE
Add custom parameter namespace declaration for legacy/java systems

### PR DESCRIPTION
**Pull request by xumix**
eg.
``` 
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:dow="http://DownloadService/">
   <soapenv:Header/>
   <soapenv:Body>
      <dow:DataProcessingComplete>
         <fileURL>--URL--</fileURL>
      </dow:DataProcessingComplete>
   </soapenv:Body>
</soapenv:Envelope>
```

### CODE REVIEW

**Comment by kotovaleksandr** [comment]
Thanks for contributing!

**Comment by xumix** [comment]
@kotovaleksandr Make a new nuget package, please :)

**Comment by kotovaleksandr** [comment]
Done https://www.nuget.org/packages/SoapCore/0.9.5

**Comment by xumix** [comment]
thanks!

**Pull request merged**
